spring.application.name=SPLITWISE-EQUALLY

# ============================
# Server Config
# ============================
server.port=8080

# ============================
# MongoDB Atlas Config ?  
# Database name = "Splitwise"
# Password = 0123459  
# ============================
spring.data.mongodb.uri=mongodb+srv://NAVRATAN_KS:0123459@mastercluster.8qkfx0e.mongodb.net/Splitwise?retryWrites=true&w=majority

# ============================
# CORS
# ============================
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
